package flyweight.simple.tree;

import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.io.StringBufferInputStream;

public class Client {
	public static void main(String[] args) {
//		FlyweightFactory factory = FlyweightFactory.genInstance();
//		factory.creatTree(100);
//		factory.creatTree(100);
//		factory.creatTree(100);
//		
//		factory.creatTree(50);
//		factory.creatTree(50);
//		factory.creatTree(50);
//		factory.creatTree(50);
		String resource = "GGTTAATTCCTTATAGGGGCGATTGGGCCCTCTAGATGCATGCTCGAGCGGCCGCCAGTGTGATGGATATCTGCAGAATTGCCCTTCCCACGGCTGATTGATGAGATGTTTGATGAGAGCTTGAAGGACCGACTGGTACCCAAGGCATGGCGCTCAGCTGAGCTACCCTACGGCCATGACTACTTCCTGGAGAACGTGGTAGACCCCAGCCATGTGGTGGTGTCCCATCACAACATCGTGGGCAACCGGTACACCGACCCCTCCTTCATCGATCTGCAGCAGCAGAAGCCTTTGAACAGAGAGGAGGGCTTCCAATTCCAAAACCTGCGCAACAAGAACATCGACGGGACCCCTGCTAAGAATGGAGTGACCATCACCACCGACTTCAAGCCGCCCTGCCTTGTTCGCATCTCCAGTGTGGATGAGGCGGGAGCTCAGACTATCTTGGCCCTGTACTCCACGCCCTCCCGCCCGGGCTACACACGCCACGTGGGCGCCCAGATCTTCGTGGAGGGGCGCAATGGCAAGAAGTCCAAGGGGCTTGGAGTCTTCAGCCTGCCCCTGCCCATATGGCTCCTGCACCTTATGGGGCCTGCCTTTCTTCACCAGGACGCTGTGTTCCTTCACTGGCAGGAGAAGATCGCGGCACGGGGCAAGATGGGCAGCCAGCGCGCTGTGGACAAGTACTTCACACCTACCAGTGCTGACAAAATGGTGTTGGCATTGAGGCAATGGCTGGAGCGCTTCAGCCCTGCAGGCGTGCCCTTTTATGGCGCCTACGCCAATGCCCCACTGCCAGAGGTGGAACGTGACCCTGCCAAGCTATTCGACACCTGGAACGCCCACACCAAGCACTGCAAGATCTGCAAGAAAGCGCATGACAACATGGAGAAGTTGCAGCCAGTGGCCTGGCCATAGCTGCGGTGGCAGCTATGCAAGCCGCCATCATCGGGGCCAGCAGCGCTGCTGCCAAGGCCAGTGCCCTGCCGCTGCTGGAGCAAGTGTGGGCACAGCCACCACCACCGCAG";
		StringBuilder sb = new StringBuilder();
		for (int i = resource.length() - 1; i >= 0; i--) {
			char c = resource.charAt(i);
			sb.append(c);
		}
		System.out.println(sb);
	}
	
	public void some() throws FileNotFoundException{
		InputStream is = new BufferedInputStream(new FileInputStream("sdf"));
	}
}
